### ISSUE TITLE
Add installation instructions to readme 

### ISSUE THREAD

**Issue by anLizard** [Saiyato/volumio-snapclient-plugin#2]
People not experienced with Volumio plugin installation are likely to have trouble without instructions.
Here's how I installed it, based onthe instructions from the [old snapcast plugin ](https://github.com/Saiyato/volumio-snapcast-plugin)

1. SSH into your Volumio instance and execute these commands:
2. `git clone https://github.com/Saiyato/volumio-snapclient-plugin.git`
3. `cd volumio-snapclient-plugin`
4. `rm volumio-snapcast-plugin.zip`
5. `volumio plugin install`
6. When you see "Finalizing Installation", wait about 30-60 seconds. CRTL+C if you are stuck at this point

also just noticed the readme says **volumio-snapserver-plugin** instead of client!

**Comment by Saiyato** [comment]
Well actually the Volumio team asked me to remove those :wink:
But you can find detailed instructions (and scripts) here: https://github.com/Saiyato/volumio-plugin-helper
